name = "TimeSeriesAnalysis"
uuid = "f3d36b1f-bec3-40b3-a6d9-6e9a057b4ae3"
authors = ["Anikaith Bhardwaj <anikaith198@gmail.com>"]
version = "0.1.0"

[deps]
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"

[compat]
TimeSeries = "0.24.2"
