name = "SurvivalAnalysis"
uuid = "94e6cfb0-adcf-4052-a1fc-3955cb9d4334"
authors = ["Anikaith Bhardwaj <anikaith198@gmail.com>"]
version = "0.1.0"

[deps]
Survival = "8a913413-2070-5976-9d4c-2b364fdc2f7f"

[compat]
Survival = "0.3.0"
